# Site settings
title: Fluent Bit
email: eduardo@treasure-data.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fluentbit.io"
twitter_username: fluentbit
github_username:  fluent

# Blog
permalink: /blog/:year/:month/:day/:title/

# Build settings
#markdown: kramdown
markdown: redcarpet
flb_major       : "0.14"
flb_version     : 0.14.7
flb_release_date: Nov 09, 2018
